@startuml

node rp as "Process" {
  component mq as "RabbitMQ"
}
node cop as "Process" {
  component co as "Controller"
}
node csp as "Process" {
  component cs as "Client Service"
  file Weather
  file Stations
}
node ewp as "Process *" {
  component ew as "Worker"

}
node awp as "Process" {
  component aw as "Aggregator"
}

cs <-> mq
mq <-> co
mq <--> ew
mq <--> aw
cs --> ew

cs <-- Weather
cs <-- Stations

@enduml