@startuml

node rp as "Process" {
  component mq as "RabbitMQ"
}
node cop as "Process" {
  component co as "Controller"
}
node csp as "Process" {
  component cs as "Client Service"
}
node ewp as "Process *" {
  component ew as "Enrichment Worker"
  file Weather
  file Stations
}
node fwp as "Process *" {
  component fw as "Formatter Worker"
}
node awp as "Process" {
  component aw as "Aggregation Worker"
}

cs <-> mq
mq <-> co
mq <--> ew
mq <--> aw
mq <--> fw

ew <-- Weather
ew <-- Stations

@enduml