@startuml

<style>
hexagon {
  BackGroundColor #00000055
  LineThickness 0
  LineColor none
}
</style>

actor User #666666

frame system  {
  agent controller #lightblue
  queue requests #lightblue
  hexagon t1 as " "
  hexagon t2 as " " 
  hexagon t3 as " "

  boundary console
  agent cs as "Client\nService"
  queue trips
  collections ew as "Worker"
  queue stats
  agent aw as "Aggregator"

  entity ts as "trip stream"
  file Weather #moccasin
  file Stations #moccasin

  queue results #aaeeaa
}

User -> console
console <- cs
cs -> trips
trips -> ew
ew -> stats
stats -> aw

aw --> results
cs <-- results

requests -> controller #darkred
requests <--- cs #darkred
requests <--- ew #darkred

ts -up-> cs
Weather --> cs #orange
Stations --> cs #orange

cs =>> ew #orange

t1 --> trips #darkblue
t3 --> stats #darkblue
t1 -ri- t2 #darkblue
t2 -ri- t3 #darkblue
controller -- t2 #darkblue

@enduml