version: "3.9"
name: distribuidos-tp1

services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    networks:
      - dtp1_net

  worker:
    container_name: worker
    image: worker:latest
    entrypoint: python3 /main.py
    networks:
      - dtp1_net

networks:
  dtp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
