version: "3.9"
name: distribuidos-tp1

services:
  worker:
    image: worker:latest
    entrypoint: python3 /main.py
    networks:
      - dtp1_net
    scale: 2

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    networks:
      - dtp1_net
    volumes:
      - ./data:/data
    depends_on:
      - worker

networks:
  dtp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
